# coding: utf-8

"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kleister
from kleister.models.user_pack_params import UserPackParams  # noqa: E501
from kleister.rest import ApiException


class TestUserPackParams(unittest.TestCase):
    """UserPackParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserPackParams(self):
        """Test UserPackParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kleister.models.user_pack_params.UserPackParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
