# coding: utf-8

"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: kleister@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kleister.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_external_callback(self) -> None:
        """Test case for external_callback

        Callback for external authentication
        """
        pass

    def test_external_initialize(self) -> None:
        """Test case for external_initialize

        Initialize the external authentication
        """
        pass

    def test_login_auth(self) -> None:
        """Test case for login_auth

        Authenticate an user by credentials
        """
        pass

    def test_refresh_auth(self) -> None:
        """Test case for refresh_auth

        Refresh an auth token before it expires
        """
        pass

    def test_verify_auth(self) -> None:
        """Test case for verify_auth

        Verify validity for an authentication token
        """
        pass


if __name__ == '__main__':
    unittest.main()
