"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kleister
from kleister.model.user_mod_params import UserModParams


class TestUserModParams(unittest.TestCase):
    """UserModParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserModParams(self):
        """Test UserModParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserModParams()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
