# coding: utf-8

"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: kleister@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kleister.models.delete_pack_from_group_request import DeletePackFromGroupRequest

class TestDeletePackFromGroupRequest(unittest.TestCase):
    """DeletePackFromGroupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeletePackFromGroupRequest:
        """Test DeletePackFromGroupRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeletePackFromGroupRequest`
        """
        model = DeletePackFromGroupRequest()
        if include_optional:
            return DeletePackFromGroupRequest(
                group = ''
            )
        else:
            return DeletePackFromGroupRequest(
                group = '',
        )
        """

    def testDeletePackFromGroupRequest(self):
        """Test DeletePackFromGroupRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
