# coding: utf-8

"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: kleister@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kleister.api.forge_api import ForgeApi


class TestForgeApi(unittest.TestCase):
    """ForgeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ForgeApi()

    def tearDown(self) -> None:
        pass

    def test_attach_forge_to_build(self) -> None:
        """Test case for attach_forge_to_build

        Attach a build to a Forge version
        """
        pass

    def test_delete_forge_from_build(self) -> None:
        """Test case for delete_forge_from_build

        Unlink a build from a Forge version
        """
        pass

    def test_list_forge_builds(self) -> None:
        """Test case for list_forge_builds

        Fetch the builds attached to a Forge version
        """
        pass

    def test_list_forges(self) -> None:
        """Test case for list_forges

        Fetch the available Forge versions
        """
        pass

    def test_update_forge(self) -> None:
        """Test case for update_forge

        Update the available Forge versions
        """
        pass


if __name__ == '__main__':
    unittest.main()
