"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kleister
from kleister.model.user_mod import UserMod


class TestUserMod(unittest.TestCase):
    """UserMod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserMod(self):
        """Test UserMod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserMod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
