"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kleister
from kleister.model.team_pack_params import TeamPackParams


class TestTeamPackParams(unittest.TestCase):
    """TeamPackParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamPackParams(self):
        """Test TeamPackParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TeamPackParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
