# coding: utf-8

"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: kleister@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kleister.api.quilt_api import QuiltApi


class TestQuiltApi(unittest.TestCase):
    """QuiltApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuiltApi()

    def tearDown(self) -> None:
        pass

    def test_attach_quilt_to_build(self) -> None:
        """Test case for attach_quilt_to_build

        Attach a build to a Quilt version
        """
        pass

    def test_delete_quilt_from_build(self) -> None:
        """Test case for delete_quilt_from_build

        Unlink a build from a Quilt version
        """
        pass

    def test_list_quilt_builds(self) -> None:
        """Test case for list_quilt_builds

        Fetch the builds attached to a Quilt version
        """
        pass

    def test_list_quilts(self) -> None:
        """Test case for list_quilts

        Fetch the available Quilt versions
        """
        pass

    def test_update_quilt(self) -> None:
        """Test case for update_quilt

        Update the available Quilt versions
        """
        pass


if __name__ == '__main__':
    unittest.main()
