# coding: utf-8

"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: kleister@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kleister.models.list_user_mods200_response import ListUserMods200Response

class TestListUserMods200Response(unittest.TestCase):
    """ListUserMods200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListUserMods200Response:
        """Test ListUserMods200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListUserMods200Response`
        """
        model = ListUserMods200Response()
        if include_optional:
            return ListUserMods200Response(
                total = 56,
                limit = 56,
                offset = 56,
                user = kleister.models.user.User(
                    id = '', 
                    username = '', 
                    password = '', 
                    email = '', 
                    fullname = '', 
                    profile = '', 
                    admin = True, 
                    active = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    auths = [
                        kleister.models.user_auth.User Auth(
                            provider = '', 
                            ref = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], ),
                mods = [
                    kleister.models.user_mod.User Mod(
                        user_id = '', 
                        user = kleister.models.user.User(
                            id = '', 
                            username = '', 
                            password = '', 
                            email = '', 
                            fullname = '', 
                            profile = '', 
                            admin = True, 
                            active = True, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            auths = [
                                kleister.models.user_auth.User Auth(
                                    provider = '', 
                                    ref = '', 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], ), 
                        mod_id = '', 
                        mod = kleister.models.mod.Mod(
                            id = '', 
                            avatar = kleister.models.mod_avatar.Mod Avatar(
                                slug = '', 
                                url = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            slug = '', 
                            name = '', 
                            side = '', 
                            description = '', 
                            author = '', 
                            website = '', 
                            donate = '', 
                            public = True, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        perm = 'user', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ListUserMods200Response(
                total = 56,
                limit = 56,
                offset = 56,
                mods = [
                    kleister.models.user_mod.User Mod(
                        user_id = '', 
                        user = kleister.models.user.User(
                            id = '', 
                            username = '', 
                            password = '', 
                            email = '', 
                            fullname = '', 
                            profile = '', 
                            admin = True, 
                            active = True, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            auths = [
                                kleister.models.user_auth.User Auth(
                                    provider = '', 
                                    ref = '', 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], ), 
                        mod_id = '', 
                        mod = kleister.models.mod.Mod(
                            id = '', 
                            avatar = kleister.models.mod_avatar.Mod Avatar(
                                slug = '', 
                                url = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                            slug = '', 
                            name = '', 
                            side = '', 
                            description = '', 
                            author = '', 
                            website = '', 
                            donate = '', 
                            public = True, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                        perm = 'user', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testListUserMods200Response(self):
        """Test ListUserMods200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
