# coding: utf-8

"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kleister
from kleister.models.mod_team_params import ModTeamParams  # noqa: E501
from kleister.rest import ApiException


class TestModTeamParams(unittest.TestCase):
    """ModTeamParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModTeamParams(self):
        """Test ModTeamParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kleister.models.mod_team_params.ModTeamParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
