# coding: utf-8

"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: kleister@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kleister.models.attach_minecraft_to_build_request import AttachMinecraftToBuildRequest

class TestAttachMinecraftToBuildRequest(unittest.TestCase):
    """AttachMinecraftToBuildRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttachMinecraftToBuildRequest:
        """Test AttachMinecraftToBuildRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttachMinecraftToBuildRequest`
        """
        model = AttachMinecraftToBuildRequest()
        if include_optional:
            return AttachMinecraftToBuildRequest(
                pack = '',
                build = ''
            )
        else:
            return AttachMinecraftToBuildRequest(
                pack = '',
                build = '',
        )
        """

    def testAttachMinecraftToBuildRequest(self):
        """Test AttachMinecraftToBuildRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
