# coding: utf-8

"""
    Kleister OpenAPI

    API definition for Kleister, manage mod packs for Minecraft

    The version of the OpenAPI document: 1.0.0-alpha1
    Contact: kleister@webhippie.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kleister.api.team_api import TeamApi


class TestTeamApi(unittest.TestCase):
    """TeamApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamApi()

    def tearDown(self) -> None:
        pass

    def test_attach_team_to_mod(self) -> None:
        """Test case for attach_team_to_mod

        Attach a mod to team
        """
        pass

    def test_attach_team_to_pack(self) -> None:
        """Test case for attach_team_to_pack

        Attach a pack to team
        """
        pass

    def test_attach_team_to_user(self) -> None:
        """Test case for attach_team_to_user

        Attach a user to team
        """
        pass

    def test_create_team(self) -> None:
        """Test case for create_team

        Create a new team
        """
        pass

    def test_delete_team(self) -> None:
        """Test case for delete_team

        Delete a specific team
        """
        pass

    def test_delete_team_from_mod(self) -> None:
        """Test case for delete_team_from_mod

        Unlink a mod from team
        """
        pass

    def test_delete_team_from_pack(self) -> None:
        """Test case for delete_team_from_pack

        Unlink a pack from team
        """
        pass

    def test_delete_team_from_user(self) -> None:
        """Test case for delete_team_from_user

        Unlink a user from team
        """
        pass

    def test_list_team_mods(self) -> None:
        """Test case for list_team_mods

        Fetch all mods attached to team
        """
        pass

    def test_list_team_packs(self) -> None:
        """Test case for list_team_packs

        Fetch all packs attached to team
        """
        pass

    def test_list_team_users(self) -> None:
        """Test case for list_team_users

        Fetch all users attached to team
        """
        pass

    def test_list_teams(self) -> None:
        """Test case for list_teams

        Fetch all available teams
        """
        pass

    def test_permit_team_mod(self) -> None:
        """Test case for permit_team_mod

        Update mod perms for team
        """
        pass

    def test_permit_team_pack(self) -> None:
        """Test case for permit_team_pack

        Update pack perms for team
        """
        pass

    def test_permit_team_user(self) -> None:
        """Test case for permit_team_user

        Update user perms for team
        """
        pass

    def test_show_team(self) -> None:
        """Test case for show_team

        Fetch a specific team
        """
        pass

    def test_update_team(self) -> None:
        """Test case for update_team

        Update a specific team
        """
        pass


if __name__ == '__main__':
    unittest.main()
